/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.CardLayout;
import java.awt.Container;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author hesac
 */
public class DichVubaoDuongPanel extends javax.swing.JPanel {

    /**
     * Creates new form DichVubaoDuongPanel
     */
    public DichVubaoDuongPanel() {
        initComponents();
    }
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField_MaDichVuBaoDuong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_PhiDichVuBaoDuong = new javax.swing.JTextField();
        jComboBox_LoaiXe = new javax.swing.JComboBox<>();
        jTextField_TenDichVuBaoDuong = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton_LuuDichVuBaoDuong = new javax.swing.JButton();
        jCheckBox_TrangThaiSuDungDichVuBaoDuong = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jButton_ThemDichVubaoDUongMoi = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_TimKiemDichVuBaoDuong = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_DanhSachDichVuBaoDuong = new javax.swing.JTable();
        jTextField_NgayCapNhat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField_MaLoaiXe = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_LoaiXe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton_LuuLoaiXe = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox_TrangThaiSuDungLaoiXe = new javax.swing.JCheckBox();
        jButton_ThemLoaiXemoi = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_DanhSachLoaiXe = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel3.setBackground(new java.awt.Color(248, 164, 136));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Danh sách dịch vụ bảo dưỡng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jTextField_MaDichVuBaoDuong.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_MaDichVuBaoDuong.setEditable(false);

        jLabel6.setText("Mã:");

        jTextField_PhiDichVuBaoDuong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_PhiDichVuBaoDuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PhiDichVuBaoDuongActionPerformed(evt);
            }
        });

        jComboBox_LoaiXe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_TenDichVuBaoDuong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_TenDichVuBaoDuong.setAutoscrolls(false);
        jTextField_TenDichVuBaoDuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TenDichVuBaoDuongActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Tên dịch vụ bảo dưỡng:");

        jButton_LuuDichVuBaoDuong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_LuuDichVuBaoDuong.setText("Lưu");

        jCheckBox_TrangThaiSuDungDichVuBaoDuong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox_TrangThaiSuDungDichVuBaoDuong.setText("Được sử dụng");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Trạng Thái:");

        jButton_ThemDichVubaoDUongMoi.setBackground(new java.awt.Color(204, 204, 255));
        jButton_ThemDichVubaoDUongMoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButton_ThemDichVubaoDUongMoi.setText("Thêm mới ...");
        jButton_ThemDichVubaoDUongMoi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jButton_ThemDichVubaoDUongMoi.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Phí dịch vụ:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Loại xe:");

        jLabel8.setText("Tìm kiếm: ");

        jTable_DanhSachDichVuBaoDuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên dịch vụ", "Phí dịch vụ", "Loại xe", "Trạng Thái", "Ngày cập nhật"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_DanhSachDichVuBaoDuong.setRowHeight(30);
        jTable_DanhSachDichVuBaoDuong.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_DanhSachDichVuBaoDuong.setShowGrid(true);
        jTable_DanhSachDichVuBaoDuong.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable_DanhSachDichVuBaoDuong);

        jTextField_NgayCapNhat.setEditable(false);

        jLabel10.setText("Ngày cập nhật");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField_TimKiemDichVuBaoDuong, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGap(933, 933, 933)
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField_NgayCapNhat))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField_TenDichVuBaoDuong, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(43, 43, 43)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(jTextField_PhiDichVuBaoDuong, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(53, 53, 53)
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField_MaDichVuBaoDuong, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(155, 155, 155)))
                                    .addComponent(jComboBox_LoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(44, 44, 44)
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCheckBox_TrangThaiSuDungDichVuBaoDuong)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(486, 486, 486)
                                .addComponent(jButton_LuuDichVuBaoDuong, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_ThemDichVubaoDUongMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_MaDichVuBaoDuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_TenDichVuBaoDuong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_LoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_PhiDichVuBaoDuong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jCheckBox_TrangThaiSuDungDichVuBaoDuong))
                .addGap(81, 81, 81)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_LuuDichVuBaoDuong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_NgayCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(82, 82, 82)
                .addComponent(jButton_ThemDichVubaoDUongMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_TimKiemDichVuBaoDuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(90, 168, 151));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Danh sách các loại xe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jTextField_MaLoaiXe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_MaDichVuBaoDuong.setEditable(false);

        jLabel9.setText("Mã:");

        jTextField_LoaiXe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Tên loại xe:");

        jButton_LuuLoaiXe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_LuuLoaiXe.setText("Lưu");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Trạng Thái:");

        jCheckBox_TrangThaiSuDungLaoiXe.setText("Được sử dụng");

        jButton_ThemLoaiXemoi.setBackground(new java.awt.Color(204, 204, 255));
        jButton_ThemLoaiXemoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButton_ThemLoaiXemoi.setText("Thêm mới ...");
        jButton_ThemLoaiXemoi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton_ThemLoaiXemoi.setOpaque(true);

        jTable_DanhSachLoaiXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã loại xe", "Tên loại xe", "Trangj thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_DanhSachLoaiXe.setRowHeight(30);
        jTable_DanhSachLoaiXe.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_DanhSachLoaiXe.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_DanhSachLoaiXe.setShowGrid(true);
        jTable_DanhSachLoaiXe.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable_DanhSachLoaiXe);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_ThemLoaiXemoi, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_LoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox_TrangThaiSuDungLaoiXe))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_LuuLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_MaLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177)))
                .addGap(66, 66, 66))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_MaLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_LoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jCheckBox_TrangThaiSuDungLaoiXe))
                .addGap(70, 70, 70)
                .addComponent(jButton_LuuLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(jButton_ThemLoaiXemoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_TenDichVuBaoDuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TenDichVuBaoDuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TenDichVuBaoDuongActionPerformed

    private void jTextField_PhiDichVuBaoDuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PhiDichVuBaoDuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PhiDichVuBaoDuongActionPerformed

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JTextField getjTextField_NgayCapNhat() {
        return jTextField_NgayCapNhat;
    }

    public void setjTextField_NgayCapNhat(JTextField jTextField_NgayCapNhat) {
        this.jTextField_NgayCapNhat = jTextField_NgayCapNhat;
    }

    public JButton getjButton_LuuLoaiXe() {
        return jButton_LuuLoaiXe;
    }

    public void setjButton_LuuLoaiXe(JButton jButton_LuuLoaiXe) {
        this.jButton_LuuLoaiXe = jButton_LuuLoaiXe;
    }

    public JLabel getjButton_ThemLoaiXemoi() {
        return jButton_ThemLoaiXemoi;
    }

    public void setjButton_ThemLoaiXemoi(JLabel jButton_ThemLoaiXemoi) {
        this.jButton_ThemLoaiXemoi = jButton_ThemLoaiXemoi;
    }



    public JButton getjButton7() {
        return jButton_LuuLoaiXe;
    }

    public void setjButton7(JButton jButton7) {
        this.jButton_LuuLoaiXe = jButton7;
    }

    public JButton getjButton_LuuDichVuBaoDuong() {
        return jButton_LuuDichVuBaoDuong;
    }

    public void setjButton_LuuDichVuBaoDuong(JButton jButton_LuuDichVuBaoDuong) {
        this.jButton_LuuDichVuBaoDuong = jButton_LuuDichVuBaoDuong;
    }

    public JLabel getjButton_ThemDichVubaoDUongMoi() {
        return jButton_ThemDichVubaoDUongMoi;
    }

    public void setjButton_ThemDichVubaoDUongMoi(JLabel jButton_ThemDichVubaoDUongMoi) {
        this.jButton_ThemDichVubaoDUongMoi = jButton_ThemDichVubaoDUongMoi;
    }

    public JCheckBox getjCheckBox_TrangThaiSuDungDichVuBaoDuong() {
        return jCheckBox_TrangThaiSuDungDichVuBaoDuong;
    }

    public void setjCheckBox_TrangThaiSuDungDichVuBaoDuong(JCheckBox jCheckBox_TrangThaiSuDungDichVuBaoDuong) {
        this.jCheckBox_TrangThaiSuDungDichVuBaoDuong = jCheckBox_TrangThaiSuDungDichVuBaoDuong;
    }

    public JCheckBox getjCheckBox_TrangThaiSuDungLaoiXe() {
        return jCheckBox_TrangThaiSuDungLaoiXe;
    }

    public void setjCheckBox_TrangThaiSuDungLaoiXe(JCheckBox jCheckBox_TrangThaiSuDungLaoiXe) {
        this.jCheckBox_TrangThaiSuDungLaoiXe = jCheckBox_TrangThaiSuDungLaoiXe;
    }

    public JComboBox<String> getjComboBox_LoaiXe() {
        return jComboBox_LoaiXe;
    }

    public void setjComboBox_LoaiXe(JComboBox<String> jComboBox_LoaiXe) {
        this.jComboBox_LoaiXe = jComboBox_LoaiXe;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JTextField getjTextField_MaLoaiXe() {
        return jTextField_MaLoaiXe;
    }

    public void setjTextField_MaLoaiXe(JTextField jTextField_MaLoaiXe) {
        this.jTextField_MaLoaiXe = jTextField_MaLoaiXe;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JTextField getjTextField_TimKiemDichVuBaoDuong() {
        return jTextField_TimKiemDichVuBaoDuong;
    }

    public void setjTextField_TimKiemDichVuBaoDuong(JTextField jTextField_TimKiemDichVuBaoDuong) {
        this.jTextField_TimKiemDichVuBaoDuong = jTextField_TimKiemDichVuBaoDuong;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JTextField getjTextField_MaDichVuBaoDuong() {
        return jTextField_MaDichVuBaoDuong;
    }

    public void setjTextField_MaDichVuBaoDuong(JTextField jTextField_MaDichVuBaoDuong) {
        this.jTextField_MaDichVuBaoDuong = jTextField_MaDichVuBaoDuong;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }


    public JTable getjTable_DanhSachDichVuBaoDuong() {
        return jTable_DanhSachDichVuBaoDuong;
    }

    public void setjTable_DanhSachDichVuBaoDuong(JTable jTable1) {
        this.jTable_DanhSachDichVuBaoDuong = jTable1;
    }

    public JTable getjTable_DanhSachLoaiXe() {
        return jTable_DanhSachLoaiXe;
    }

    public void setjTable_DanhSachLoaiXe(JTable jTable2) {
        this.jTable_DanhSachLoaiXe = jTable2;
    }

    public JTextField getjTextField1() {
        return jTextField_MaDichVuBaoDuong;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.jTextField_MaDichVuBaoDuong = jTextField1;
    }

    public JTextField getjTextField_LoaiXe() {
        return jTextField_LoaiXe;
    }

    public void setjTextField_LoaiXe(JTextField jTextField_LoaiXe) {
        this.jTextField_LoaiXe = jTextField_LoaiXe;
    }

    public JTextField getjTextField_PhiDichVuBaoDuong() {
        return jTextField_PhiDichVuBaoDuong;
    }

    public void setjTextField_PhiDichVuBaoDuong(JTextField jTextField_PhiDichVuBaoDuong) {
        this.jTextField_PhiDichVuBaoDuong = jTextField_PhiDichVuBaoDuong;
    }

    public JTextField getjTextField_TenDichVuBaoDuong() {
        return jTextField_TenDichVuBaoDuong;
    }

    public void setjTextField_TenDichVuBaoDuong(JTextField jTextField_TenDichVuBaoDuong) {
        this.jTextField_TenDichVuBaoDuong = jTextField_TenDichVuBaoDuong;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_LuuDichVuBaoDuong;
    private javax.swing.JButton jButton_LuuLoaiXe;
    private javax.swing.JLabel jButton_ThemDichVubaoDUongMoi;
    private javax.swing.JLabel jButton_ThemLoaiXemoi;
    private javax.swing.JCheckBox jCheckBox_TrangThaiSuDungDichVuBaoDuong;
    private javax.swing.JCheckBox jCheckBox_TrangThaiSuDungLaoiXe;
    private javax.swing.JComboBox<String> jComboBox_LoaiXe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_DanhSachDichVuBaoDuong;
    private javax.swing.JTable jTable_DanhSachLoaiXe;
    private javax.swing.JTextField jTextField_LoaiXe;
    private javax.swing.JTextField jTextField_MaDichVuBaoDuong;
    private javax.swing.JTextField jTextField_MaLoaiXe;
    private javax.swing.JTextField jTextField_NgayCapNhat;
    private javax.swing.JTextField jTextField_PhiDichVuBaoDuong;
    private javax.swing.JTextField jTextField_TenDichVuBaoDuong;
    private javax.swing.JTextField jTextField_TimKiemDichVuBaoDuong;
    // End of variables declaration//GEN-END:variables

}
