/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import javax.swing.*;

/**
 *
 * @author hesac
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainView() {
        
        initComponents();
        initView();
        setLayout(new GridLayout(1, 1));
        setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    public JPanel getdichVuBaoDuongPanel() {
        return donBaoDuongPanel;
    }

    public void setdichVuBaoDuongPanel(JPanel DonBaoDuongPanel) {
        this.donBaoDuongPanel = DonBaoDuongPanel;
    }

    public JPanel getDonBaoDuongPanel() {
        return donBaoDuongPanel;
    }

    public void setDonBaoDuongPanel(JPanel donBaoDuongPanel) {
        this.donBaoDuongPanel = donBaoDuongPanel;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        donBaoDuongPanel = new View.DichVubaoDuongPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        //View.DonBaoDuong.DonBaoDuongContainerPanel();
        donBaoDuongPanel.setPreferredSize(new java.awt.Dimension(1900, 1000));
        donBaoDuongPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                donBaoDuongPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                donBaoDuongPanelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout donBaoDuongPanelLayout = new javax.swing.GroupLayout(donBaoDuongPanel);
        donBaoDuongPanel.setLayout(donBaoDuongPanelLayout);
        donBaoDuongPanelLayout.setHorizontalGroup(
            donBaoDuongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1668, Short.MAX_VALUE)
        );
        donBaoDuongPanelLayout.setVerticalGroup(
            donBaoDuongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(donBaoDuongPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1668, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(donBaoDuongPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void donBaoDuongPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donBaoDuongPanelMouseEntered


    }//GEN-LAST:event_donBaoDuongPanelMouseEntered

    private void donBaoDuongPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donBaoDuongPanelMouseExited

    }//GEN-LAST:event_donBaoDuongPanelMouseExited

    private void initView() {
        donBaoDuongPanel.setLayout(new GridLayout(1, 4));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel donBaoDuongPanel;
    // End of variables declaration//GEN-END:variables
}
